name:                smap
version:             0.1.0
github:              "wyager/smap"
license:             BSD3
author:              "Will Yager"
maintainer:          "will@yager.io"
copyright:           "2019 Will Yager"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on GitHub at <https://github.com/wyager/smap>

default-extensions:
- TupleSections
- RankNTypes
- ScopedTypeVariables
- LambdaCase
- BangPatterns

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable
- attoparsec
- streaming
- streaming-bytestring
- streaming-attoparsec
- bytestring
- resourcet
- optparse-applicative
- transformers
- lens
- strict
- text
- siphash

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -fexpose-all-unfoldings

executables:
  smap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspecialize-aggressively
    dependencies:
    - smap

tests:
  smap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smap
